import { requestJson } from './client'
import type { Conversation, Message } from './types'
const parseConversation = (v: unknown): Conversation => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid conversation'); const o = v as Record<string, unknown>; if (typeof o.id !== 'string' || typeof o.title !== 'string' || typeof o.created_at !== 'string' || typeof o.updated_at !== 'string') throw new Error('Invalid conversation'); return o as unknown as Conversation }
export const listConversations = () => requestJson('/conversations', (v) => { if (!Array.isArray(v)) throw new Error('Invalid conversations'); return v.map(parseConversation) })
export const createConversation = () => requestJson('/conversations', parseConversation, { method: 'POST' })
const parseMessage = (v: unknown): Message => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid message'); const o = v as Record<string, unknown>; if (typeof o.id !== 'string' || typeof o.role !== 'string' || typeof o.content_markdown !== 'string' || (o.task_id !== null && typeof o.task_id !== 'string') || typeof o.created_at !== 'string') throw new Error('Invalid message'); return { id: o.id, role: o.role, content_markdown: o.content_markdown, task_id: o.task_id as string | null, created_at: o.created_at } }
export const getConversation = (id: string) => requestJson(`/conversations/${encodeURIComponent(id)}`, (v) => { const o = v as Record<string, unknown>; if (!o || !Array.isArray(o.messages)) throw new Error('Invalid conversation response'); return { conversation: parseConversation(o.conversation), messages: o.messages.map(parseMessage) } })
export const sendMessage = (id: string, content_markdown: string, client_request_id: string) => requestJson(`/conversations/${encodeURIComponent(id)}/messages`, (v) => { const o = v as Record<string, unknown>; if (!o || typeof o.task_id !== 'string') throw new Error('Invalid task response'); return { task_id: o.task_id } }, { method: 'POST', body: JSON.stringify({ content_markdown, client_request_id }) })
export const deleteConversation = (id: string) => requestJson(`/conversations/${encodeURIComponent(id)}`, () => null, { method: 'DELETE' })
